# gen-volatile-layer.ps1 — 生成 CLAUDE.md 的 VOLATILE 层
# 每次 preflight 时自动刷新记忆快照+服务状态+时间戳
# 位于 CLAUDE.md 底部，变化不影响前缀缓存
param([switch]$Json)
$ErrorActionPreference = 'Stop'

$Root = Split-Path -Parent (Split-Path -Parent $PSCommandPath)
$ClaudeMd = Join-Path (Join-Path $Root '..') 'CLAUDE.md'
$MemIndex = Join-Path (Join-Path $Root '..') 'MEMORY.md'
$MemDir = Join-Path (Join-Path $Root '..') 'memory'

# ── 1. 记忆快照 ──
$memories = @()
if (Test-Path $MemIndex) {
  $indexLines = Get-Content $MemIndex -Encoding UTF8 | Where-Object { $_ -match '^\s*-' -and $_ -notmatch '^\s*#' }
  foreach ($line in $indexLines) {
    if ($line -match '\[([^\]]+)\]\(([^)]+)\)\s*—\s*(.*)') {
      $memories += @{ name = $matches[1]; file = $matches[2]; hook = $matches[3] }
    }
  }
}
# Read last 3 memory files for details
$recentMemories = @()
$count = 0
foreach ($m in $memories) {
  if ($count -ge 5) { break }
  $memFile = Join-Path (Join-Path $Root '..') $m.file
  if (Test-Path $memFile) {
    try {
      $content = Get-Content $memFile -Raw -Encoding UTF8
      # Extract frontmatter description
      if ($content -match 'description:\s*(.*)') {
        $recentMemories += "  - **$($m.name):** $($matches[1])"
        $count++
      }
    } catch {}
  }
}

$memSection = if ($recentMemories.Count -gt 0) {
  "**最近记忆 ($($recentMemories.Count)条):**`n$($recentMemories -join "`n")"
} else {
  "**最近记忆:** (无)"
}

# ── 2. 服务状态 ──
$gptStatus = 'down'
try {
  $h = Invoke-RestMethod 'http://127.0.0.1:3000/health' -TimeoutSec 2
  $gptStatus = $h.status
} catch { $gptStatus = 'down' }

$ollamaStatus = 'down'
try {
  $o = Invoke-RestMethod 'http://127.0.0.1:11434/api/tags' -TimeoutSec 2
  $ollamaStatus = "up ($($o.models.Count) models)"
} catch { $ollamaStatus = 'down' }

$serviceSection = "GPT-5.5: $gptStatus | Ollama: $ollamaStatus | MCP: playwright, windows-cua"

# ── 3. 悬赏状态 ──
$bountySection = ''
try {
  $bountyScript = Join-Path (Join-Path $Root 'scripts') 'bounty-check.ps1'
  if (Test-Path $bountyScript) {
    $token = [Environment]::GetEnvironmentVariable("GITHUB_TOKEN","User")
    if ($token) {
      $headers = @{"Accept"="application/vnd.github.v3+json";"Authorization"="Bearer $token";"User-Agent"="volatile-layer"}
      # Quick check for open bounties
      $url = "https://api.github.com/search/issues?q=author:zhuyuhao030612+type:pr+repo:cuentaprueba244w-dotcom/TentOfTrials+is:open"
      $r = Invoke-RestMethod -Uri $url -Headers $headers -TimeoutSec 5
      if ($r.total_count -gt 0) {
        $lines = @()
        foreach ($item in $r.items) {
          $amt = if ($item.title -match '\$(\d+)') { "$$($matches[1])" } else { "?" }
          $lines += "  - PR ##$($item.number): $amt — $($item.state) ($($item.updated_at.Substring(0,10)))"
        }
        $bountySection = "**悬赏状态:**`n$($lines -join "`n")"
      }
    }
  }
} catch {}

# ── 4. 时间戳 ──
$ts = Get-Date -Format 'yyyy-MM-dd HH:mm'
$pfToken = 'N/A'
$pfStateFile = Join-Path (Join-Path $Root 'runtime') 'preflight-state.json'
if (Test-Path $pfStateFile) {
  try {
    $pf = Get-Content $pfStateFile -Raw -Encoding UTF8 | ConvertFrom-Json
    $pfToken = $pf.token.Substring(0, 8) + '...'
  } catch {}
}
$timeSection = "**会话时间:** $ts | **Preflight:** $pfToken"

# ── 5. Skills 摘要 ──
$skillSection = ''
$skillsDirs = @((Join-Path (Join-Path $Root 'skills') 'approved'), (Join-Path (Join-Path $Root 'skills') '_auto'))
$skillNames = @()
foreach ($dir in $skillsDirs) {
  if (Test-Path $dir) {
    $skillNames += Get-ChildItem $dir -Directory -ErrorAction SilentlyContinue | ForEach-Object { $_.Name }
  }
}
# Also check top-level skill dirs
$topSkills = Get-ChildItem (Join-Path $Root 'skills') -Directory -ErrorAction SilentlyContinue | Where-Object { $_.Name -notin @('approved','_auto','rejected-index') }
$skillNames += $topSkills | ForEach-Object { $_.Name }
if ($skillNames.Count -gt 0) {
  $skillSection = "**可用 Skills ($($skillNames.Count)):** $($skillNames -join ', ')"
}

# ── 6. 组装 ──
$volatileContent = @"
<!-- ────────── VOLATILE LAYER (auto-generated by ai preflight) ────────── -->
<!-- VOLATILE_START -->

$timeSection

**服务状态:** $serviceSection

$memSection
$bountySection
$skillSection
<!-- VOLATILE_END -->
"@

# ── 7. 写回 CLAUDE.md ──
if (-not (Test-Path $ClaudeMd)) {
  Write-Error "CLAUDE.md not found at $ClaudeMd"
  exit 1
}

$claudeContent = Get-Content $ClaudeMd -Raw -Encoding UTF8

# Replace between markers
$pattern = '(?s)<!-- VOLATILE_START -->.*<!-- VOLATILE_END -->'
$newBlock = "<!-- VOLATILE_START -->`n`n$timeSection`n`n**服务状态:** $serviceSection`n`n$memSection"
if ($bountySection) { $newBlock += "`n`n$bountySection" }
if ($skillSection) { $newBlock += "`n`n$skillSection" }
$newBlock += "`n`n<!-- VOLATILE_END -->"

$updated = $claudeContent -replace $pattern, [regex]::Escape($newBlock)
# The -replace with [regex]::Escape would escape the newBlock. Let's do it differently.
$startMarker = '<!-- VOLATILE_START -->'
$endMarker = '<!-- VOLATILE_END -->'
$startIdx = $claudeContent.IndexOf($startMarker)
$endIdx = $claudeContent.IndexOf($endMarker)
if ($startIdx -ge 0 -and $endIdx -gt $startIdx) {
  $before = $claudeContent.Substring(0, $startIdx)
  $after = $claudeContent.Substring($endIdx + $endMarker.Length)
  $updated = $before + $newBlock + $after
  $utf8NoBom = New-Object System.Text.UTF8Encoding $false
  [System.IO.File]::WriteAllText($ClaudeMd, $updated, $utf8NoBom)
  Write-Host "[volatile] Updated CLAUDE.md volatile layer: $ts"
  Write-Host "  Memories: $($recentMemories.Count) | Skills: $($skillNames.Count) | GPT-5.5: $gptStatus | Ollama: $ollamaStatus"
  if ($bountySection) { Write-Host "  Bounties: active" }
} else {
  Write-Error "VOLATILE markers not found in CLAUDE.md"
  exit 2
}

if ($Json) {
  @{
    updated = $true
    timestamp = $ts
    memories = $recentMemories.Count
    skills = $skillNames.Count
    gpt55 = $gptStatus
    ollama = $ollamaStatus
  } | ConvertTo-Json -Compress
}
